USE [master]
GO

/****** Object:  Database [petshop]    Script Date: 17/08/2021 19:29:22 ******/
CREATE DATABASE [petshop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'petshop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\petshop.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'petshop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\petshop_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [petshop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [petshop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [petshop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [petshop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [petshop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [petshop] SET ARITHABORT OFF 
GO

ALTER DATABASE [petshop] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [petshop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [petshop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [petshop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [petshop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [petshop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [petshop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [petshop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [petshop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [petshop] SET  DISABLE_BROKER 
GO

ALTER DATABASE [petshop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [petshop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [petshop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [petshop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [petshop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [petshop] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [petshop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [petshop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [petshop] SET  MULTI_USER 
GO

ALTER DATABASE [petshop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [petshop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [petshop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [petshop] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [petshop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [petshop] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [petshop] SET QUERY_STORE = OFF
GO

ALTER DATABASE [petshop] SET  READ_WRITE 
GO


